version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    networks:
      - base
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    networks:
      - base
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /chat
  nginx:
    image: nginx:latest
    environment:
      TZ: Asia/Tokyo
    networks:
      - base
    ports:
      - "3000:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - base
    volumes:
      - "./redis/data:/data"
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    networks:
      - base

networks:
  base:
