version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    networks:
      - base
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    networks:
      - base
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /chat
      - /var/log/app
  nginx:
    image: nginx:latest
    environment:
      TZ: Asia/Tokyo
    networks:
      - base
    ports:
      - "3000:80"
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: "redis:latest"
    environment:
      TZ: Asia/Tokyo
    ports:
      - "6379:6379"
    networks:
      - base
    volumes:
      - "./redis/data:/data"
  pra:
    image: erikdubbelboer/phpredisadmin
    environment:
      TZ: Asia/Tokyo
      REDIS_1_HOST: redis
      REDIS_1_NAME: redis
    ports:
      - 8002:80
    networks:
      - base

networks:
  base:
